### ISSUE TITLE
Help please!  "libmr.so is not found"

### ISSUE THREAD

**Issue by Alabenba** [aadeshnpn/OSDN#11]
Hi, I'm interested in this work very much and tried to reproduce it. But unfortunately, I met this problem. How can I fix it? 
![image](https://user-images.githubusercontent.com/64249094/92296727-140a1b80-ef6a-11ea-916b-90168972f94c.png)
ps: I followed your steps carefully.

**Comment by aadeshnpn** [comment]
Thanks @Alabenba.
Hopefully this will solve the issue you are having. 
`libmr.so` is a library file which is located in utils folder (https://github.com/aadeshnpn/OSDN/blob/master/utils/libmr.cpython-36m-x86_64-linux-gnu.so). I am sure that it works fine in Linux. Looks like you are using windows. Hopefully copying the `libmr.so` in the main directory would resolve your issue.

**Comment by Alabenba** [comment]
Hi, thanks for your reply. I have tried it in Linux this time, but unfortunately, the same issue still occurred. I guess it might be caused by the mismatched python version (I use python2.7), but I'm not sure. Would you tell me how to compile the libmr.so for python2? Or, how to fix it if it is not for the reason? Thanks!

![image](https://user-images.githubusercontent.com/64249094/92548729-5a24ef00-f28a-11ea-97da-1b3aa43a9217.png)

**Comment by aadeshnpn** [comment]
@Alabenba Nice catch!  LibMR should be compiled from the original repository https://github.com/abhijitbendale/OSDN. I think using Python 3.6 should solve this libmr.so not found issue.

**Comment by Alabenba** [comment]
Yes, using Python3.6 can make it work. And I tried recompile libmr.so for python2, it also works.
