### ISSUE TITLE
how to use pytorch to achieve the repo?

### ISSUE THREAD

**Issue by shining-love** [aadeshnpn/OSDN#16]
Thanks for your really good work! Is it possible to transfer form keras to pytorch? Pytorch was actually very popular, but Keras wasn't. Many advanced target detection systems are now pyTorch's domain.

**Comment by aadeshnpn** [comment]
Thanks @yang-gis . I think its possible to transfer from Keras to Pytorch and it shouldn't be that difficult. I am kind of busy in coming weeks with finals and deadlines. Feel free to port the code from Keras to Pytorch. I will accept the pull request. I might port the code to PyTorch in coming months. Maybe following points would be useful to port the code to PyTorch:
* The DNN model is classic LeNet. First, we need to write LeNet into PyTorch.
* I believe the distance computation and welbull fitting is pure python code so not much changes is required
* Then the pipeline needs to be made PyTorch compatible.

**Comment by shining-love** [comment]
> Thanks @yang-gis . I think its possible to transfer from Keras to Pytorch and it shouldn't be that difficult. I am kind of busy in coming weeks with finals and deadlines. Feel free to port the code from Keras to Pytorch. I will accept the pull request. I might port the code to PyTorch in coming months. Maybe following points would be useful to port the code to PyTorch:
> 
> * The DNN model is classic LeNet. First, we need to write LeNet into PyTorch.
> * I believe the distance computation and welbull fitting is pure python code so not much changes is required
> * Then the pipeline needs to be made PyTorch compatible.

Thanks for your kind reply! I will do some work by following your guides.Meanwhile, It is worth to expect your next work for tansering keras to pytorch.

**Comment by aadeshnpn** [comment]
Thanks @yang-gis. Great!
